# =========================================================================================
#
#     ██████╗  █████╗ ███╗   ██╗██████╗ ██╗   ██╗ ██████╗ ██████╗ ███████╗███████╗
#     ██╔══██╗██╔══██╗████╗  ██║██╔══██╗╚██╗ ██╔╝██╔═══██╗██╔══██╗██╔════╝██╔════╝
#     ██████╔╝███████║██╔██╗ ██║██║  ██║ ╚████╔╝ ██║   ██║██████╔╝█████╗  ███████╗
#     ██╔══██╗██╔══██║██║╚██╗██║██║  ██║  ╚██╔╝  ██║   ██║██╔══██╗██╔══╝  ╚════██║
#     ██║  ██║██║  ██║██║ ╚████║██████╔╝   ██║   ╚██████╔╝██║  ██║███████╗███████║
#     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝    ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝
#
#                                 RandyOres ver1.0.0
#
# =========================================================================================



# << Block money -- How much money the player gets when mining specific block >>
BlockMoney:
  NETHERRACK: 0.01
  STONE: 0.1
  COAL_ORE: 1
  IRON_ORE: 2
  REDSTONE_ORE: 2
  NETHER_QUARTZ_ORE: 2
  NETHER_GOLD_ORE: 5
  LAPIS_ORE: 15
  GOLD_ORE: 25
  DIAMOND_ORE: 50
  ANCIENT_DEBRIS: 60
  EMERALD_ORE: 75
