name: RandyOres
version: @version@
main: ga.littlehillmyr.randyores.RandyOres
api-version: 1.16
depend:
  - Vault
author: LittleHillMYR
description: Some guy told me to make a plugin similar to MineEconomy but 1.16 updated.
permissions:
  randyores.moneyperblock:
    description: Allow players to get money when mining specific block
    default: true
